version: "3.3"
volumes:
  mysql-volume:
    driver: 'local'
services:
  mysql:
    image: mysql:8
    volumes:
      - mysql-volume:/var/lib/mysql
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: sntagger
      MYSQL_PASSWORD: dev
  redis:
    image: redis:4
    ports:
      - 6379:6379