version: "3.3"
volumes:
  mysql-volume:
    driver: 'local'
services:
  web:
    image: nginx:1.15
    ports:
      - "8000:80"
    extra_hosts:
      - "local.com:${HOST_IP}"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/logs/:/var/log/nginx/
  mysql:
    image: mysql:8
    volumes:
      - mysql-volume:/var/lib/mysql
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: historie
      MYSQL_PASSWORD: dev
  redis:
    image: redis:4
    ports:
      - 6379:6379